### ISSUE TITLE
Map with Norwegian health regions 

### ISSUE THREAD

**Issue by oyvindbusk** [folkehelseinstituttet/fhimaps#6]
Hi, 

Thanks for making this package. I am using the norway_nuts3_map_b2020_default_dt-map for some plots. Is it possible to make a map that is divided into the norwegian health-regions - and how would I go about creating that?

Øyvind

**Comment by raubreywhite** [comment]
Hi Øyvind!

Unfortunately I don't know of any easy way to do this. 

This will get you the counties colored by health regions:
```
library(ggplot2)
pd <- 
  merge(
    fhimaps::norway_nuts3_map_b2020_default_dt,
    fhidata::norway_locations_hierarchy(from="county", to="region"),
    by.x = "location_code",
    by.y= "from_code"
  )

q <- ggplot()
q <- q + geom_polygon(data = pd, aes( x = long, y = lat, group = group, fill=to_code), 
                      color="black", size=0.1)
q <- q + theme_void()
q <- q + coord_quickmap()
q <- q + labs(title = "Default layout")
q
```

But to remove the "within health region borders" is going to require some geo-libraries.

Something like: https://stackoverflow.com/questions/35794772/r-gis-find-borders-between-polygons while (probably) using `norway_nuts3_map_b2020_default_sf`

If you find out a solution, please let me know as that would be very useful :-)
